expose_php=Off
memory_limit=256M
max_execution_time=90
post_max_size=25M
upload_max_filesize=25M
realpath_cache_size=4096K
realpath_cache_ttl=600
opcache.enable=1
opcache.enable_cli=1
opcache.memory_consumption=128
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=20000
opcache.validate_timestamps=0
opcache.save_comments=1
